name: mirror

on:
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2-beta
      - name: mirror
        id: mirror
        uses: bridgelightcloud/github-mirror-action@v1
        with:
          origin: 'https://github.com/ros-controls/ros2_control.git'
          GITHUB_TOKEN: ${{ secrets.WAMV_TAN_BOT_SECRET }}